[package]
name = "pacgirls"
version = "0.1.0"
authors = ["tabs"]

[dependencies]
carboxyl = "0.2"
carboxyl_window = "0.0.3"
benzene = "0.2"
benzene-2d = "0.2"
elmesque = "0.12"
piston = "0.17"
pistoncore-input = "0.8"
